### ISSUE TITLE
No source?

### ISSUE THREAD

**Issue by D3m0n92** [jorgejgnz/PhysHand#1]
Hi, I'm following your work on Twitter. Truly a great job! When will it be possible to take a look at how the system works? :)

**Comment by jorgejgnz** [comment]
Thank you! Likely September

**Comment by benbeezy** [comment]
Well it just so happens to be September 1st and I happen to get back to this project while looking for some good physics based hand tracking for a project even if it's a pre-alpha

**Comment by jorgejgnz** [comment]
Source code is mostly completed and it will be made public during September on a new repo. It's being privately reviewed and I'm working on documentation
